# src  ./of-software/backend/of-software/docker-compose.yml
# updates
networks:
  of-software-net:
    driver: bridge

volumes:
  local_pgdata:
  pgadmin-data:
  cookies-data:

services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${DB_NAME}
    networks:
      - of-software-net
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    ports:
      - '8888:80'
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - of-software-net
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  backend:
    build: .
    env_file:
      - .env
    container_name: nest_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
      - '5900:5900'
    environment:
      - ENV=dev
      - DISPLAY=:10
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - of-software-net




