import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1749142347644 implements MigrationInterface {
    name = 'Init1749142347644'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "model_platform" DROP CONSTRAINT "FK_820e0a2905acb16f044270015c8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b4601cdfc91215aaab7d016b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_50043b98e17a364f9652c92357"`);
        await queryRunner.query(`DROP INDEX "public"."fki_FK_20cf9b2502a160a9c7e8cea1698"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_799213465ac24d007a22e65f20"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_faff6e2cf7839f391f194b70a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_58524e56bc739b71197b830ff9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_740c3c703c7205ccd211066763"`);
        await queryRunner.query(`ALTER TABLE "group_message" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "group_message" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "group_message" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "group_message" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "platform_group" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "platform_group" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "platform_group" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "platform_group" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP CONSTRAINT "UQ_820e0a2905acb16f044270015c8"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP COLUMN "post_id"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP COLUMN "number_of_days"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP COLUMN "latest_group_id"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP COLUMN "site_url"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP COLUMN "scheduled_date"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP COLUMN "prokey"`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP CONSTRAINT "PK_502c6c234a6f9e52a0ca8d1d36d"`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD CONSTRAINT "PK_3354778da0a5eb5eb21d8cc6b0e" PRIMARY KEY ("model_id", "platform_id", "id")`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD "post_id" integer`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD CONSTRAINT "UQ_820e0a2905acb16f044270015c8" UNIQUE ("post_id")`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD "username" character varying`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD "password" character varying`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD "site_url" character varying`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD "number_of_days" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD "prokey" character varying`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD "scheduled_date" character varying`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD "latest_group_id" integer`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "platform_group" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "platform_group" DROP CONSTRAINT "PK_ca6793440910de467c5545ca769"`);
        await queryRunner.query(`ALTER TABLE "platform_group" ADD CONSTRAINT "PK_ed91f72d7898d5e27ee61067cc8" PRIMARY KEY ("group_id", "platform_id", "id")`);
        await queryRunner.query(`ALTER TABLE "platform_group" ADD "status" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "platform_group" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "platform_group" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "group_message" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "group_message" DROP CONSTRAINT "PK_f25bed4abd2add675d014950d74"`);
        await queryRunner.query(`ALTER TABLE "group_message" ADD CONSTRAINT "PK_cd3ba566cb9b3767daf96a7c03c" PRIMARY KEY ("group_id", "message_id", "id")`);
        await queryRunner.query(`ALTER TABLE "group_message" ADD "status" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "group_message" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "group_message" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "group_message" DROP CONSTRAINT "PK_cd3ba566cb9b3767daf96a7c03c"`);
        await queryRunner.query(`ALTER TABLE "group_message" ADD CONSTRAINT "PK_f25bed4abd2add675d014950d74" PRIMARY KEY ("group_id", "message_id")`);
        await queryRunner.query(`ALTER TABLE "platform_group" DROP CONSTRAINT "PK_ed91f72d7898d5e27ee61067cc8"`);
        await queryRunner.query(`ALTER TABLE "platform_group" ADD CONSTRAINT "PK_ca6793440910de467c5545ca769" PRIMARY KEY ("platform_id", "group_id")`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP CONSTRAINT "PK_3354778da0a5eb5eb21d8cc6b0e"`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD CONSTRAINT "PK_502c6c234a6f9e52a0ca8d1d36d" PRIMARY KEY ("model_id", "platform_id")`);
        await queryRunner.query(`CREATE INDEX "IDX_740c3c703c7205ccd211066763" ON "group_message" ("group_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_58524e56bc739b71197b830ff9" ON "group_message" ("message_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_faff6e2cf7839f391f194b70a0" ON "platform_group" ("platform_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_799213465ac24d007a22e65f20" ON "platform_group" ("group_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_50043b98e17a364f9652c92357" ON "model_platform" ("model_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3b4601cdfc91215aaab7d016b7" ON "model_platform" ("platform_id") `);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD CONSTRAINT "FK_820e0a2905acb16f044270015c8" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "model_platform" DROP CONSTRAINT "FK_820e0a2905acb16f044270015c8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3b4601cdfc91215aaab7d016b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_50043b98e17a364f9652c92357"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_799213465ac24d007a22e65f20"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_faff6e2cf7839f391f194b70a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_58524e56bc739b71197b830ff9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_740c3c703c7205ccd211066763"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP CONSTRAINT "PK_502c6c234a6f9e52a0ca8d1d36d"`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD CONSTRAINT "PK_3354778da0a5eb5eb21d8cc6b0e" PRIMARY KEY ("model_id", "platform_id", "id")`);
        await queryRunner.query(`ALTER TABLE "platform_group" DROP CONSTRAINT "PK_ca6793440910de467c5545ca769"`);
        await queryRunner.query(`ALTER TABLE "platform_group" ADD CONSTRAINT "PK_ed91f72d7898d5e27ee61067cc8" PRIMARY KEY ("group_id", "platform_id", "id")`);
        await queryRunner.query(`ALTER TABLE "group_message" DROP CONSTRAINT "PK_f25bed4abd2add675d014950d74"`);
        await queryRunner.query(`ALTER TABLE "group_message" ADD CONSTRAINT "PK_cd3ba566cb9b3767daf96a7c03c" PRIMARY KEY ("group_id", "message_id", "id")`);
        await queryRunner.query(`ALTER TABLE "group_message" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "group_message" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "group_message" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "group_message" DROP CONSTRAINT "PK_cd3ba566cb9b3767daf96a7c03c"`);
        await queryRunner.query(`ALTER TABLE "group_message" ADD CONSTRAINT "PK_f25bed4abd2add675d014950d74" PRIMARY KEY ("group_id", "message_id")`);
        await queryRunner.query(`ALTER TABLE "group_message" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "platform_group" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "platform_group" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "platform_group" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "platform_group" DROP CONSTRAINT "PK_ed91f72d7898d5e27ee61067cc8"`);
        await queryRunner.query(`ALTER TABLE "platform_group" ADD CONSTRAINT "PK_ca6793440910de467c5545ca769" PRIMARY KEY ("group_id", "platform_id")`);
        await queryRunner.query(`ALTER TABLE "platform_group" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP COLUMN "latest_group_id"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP COLUMN "scheduled_date"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP COLUMN "prokey"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP COLUMN "number_of_days"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP COLUMN "site_url"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP CONSTRAINT "UQ_820e0a2905acb16f044270015c8"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP COLUMN "post_id"`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP CONSTRAINT "PK_3354778da0a5eb5eb21d8cc6b0e"`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD CONSTRAINT "PK_502c6c234a6f9e52a0ca8d1d36d" PRIMARY KEY ("model_id", "platform_id")`);
        await queryRunner.query(`ALTER TABLE "model_platform" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD "prokey" character varying`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD "scheduled_date" character varying`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD "site_url" character varying`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD "password" character varying`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD "username" character varying`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD "latest_group_id" integer`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD "number_of_days" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD "post_id" integer`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD CONSTRAINT "UQ_820e0a2905acb16f044270015c8" UNIQUE ("post_id")`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "platform_group" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "platform_group" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "platform_group" ADD "status" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "platform_group" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "group_message" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "group_message" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "group_message" ADD "status" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "group_message" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_740c3c703c7205ccd211066763" ON "group_message" ("group_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_58524e56bc739b71197b830ff9" ON "group_message" ("message_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_faff6e2cf7839f391f194b70a0" ON "platform_group" ("platform_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_799213465ac24d007a22e65f20" ON "platform_group" ("group_id") `);
        await queryRunner.query(`CREATE INDEX "fki_FK_20cf9b2502a160a9c7e8cea1698" ON "post_caption" ("post_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_50043b98e17a364f9652c92357" ON "model_platform" ("model_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3b4601cdfc91215aaab7d016b7" ON "model_platform" ("platform_id") `);
        await queryRunner.query(`ALTER TABLE "model_platform" ADD CONSTRAINT "FK_820e0a2905acb16f044270015c8" FOREIGN KEY ("post_id") REFERENCES "post"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
